export const LOAD = 'LOAD' as const
export const UNLOAD = 'UNLOAD' as const
export const UPDATE_ULTIMATE_NODE_POSITION =
  'UPDATE_ULTIMATE_NODE_POSITION' as const
export const UPDATE_LAST_SPREAD_INDEX = 'UPDATE_LAST_SPREAD_INDEX' as const
export const QUEUE_DEFERRED_CALLBACKS = 'QUEUE_DEFERRED_CALLBACKS' as const
export const DEQUEUE_DEFERRED_CALLBACKS = 'DEQUEUE_DEFERRED_CALLBACKS' as const
