module.exports = {
    name: 'b-ber',
    setupTestFrameworkScriptFile: 'jest-extended',
    collectCoverage: true,
    collectCoverageFrom: [
        '**/*.{js,jsx}',
        '!**/node_modules/**',
        '!**/vendor/**',
        '!**/dist/**',
        '!**/demo/**',
        '!**/demos/**',
        '!**/*.config.js**',
        '!**/*.loaders.js**',
        '!**/b-ber-lib/*.js',
        '!**/b-ber-reader/epub/**/*.js',
        '!**/b-ber-resources/*.js',
        '!**/b-ber-shapes/*.js',
        '!**/b-ber-shapes/dc/*.js',
        '!**/b-ber-shapes/directives/*.js',
        '!**/b-ber-shapes/sequences/*.js',
        '!**/b-ber-templates/*.js',
        '!**/b-ber-templates/Ncx/*.js',
        '!**/b-ber-templates/Opf/*.js',
        '!**/b-ber-templates/Ops/*.js',
        '!**/b-ber-templates/Project/*.js',
        '!**/b-ber-templates/Toc/*.js',
        '!**/b-ber-templates/Xhtml/*.js',
        '!**/b-ber-templates/Xml/*.js',
        '!**/b-ber-templates/figures/*.js',
    ],
    coveragePathIgnorePatterns: [
        '<rootDir>/packages/b-ber-connect/',
        '<rootDir>/coverage/',
        '<rootDir>/demos/',
    ],
    coverageReporters: ['html', 'lcov', 'json'],
    testEnvironment: 'jest-environment-jsdom-global',
}

