module.exports = {
  name: 'b-ber',
  verbose: true,
  setupFilesAfterEnv: ['jest-extended'],
  collectCoverage: false,
  collectCoverageFrom: [
    '**/*.{js,jsx}',
    '!**/node_modules/**',
    '!**/vendor/**',
    '!**/dist/**',
    '!**/demo/**',
    '!**/demos/**',
    '!**/*.config.js**',
    '!**/*.loaders.js**',
    '!**/b-ber-lib/*.js',
    '!**/b-ber-reader/epub/**/*.js',
    '!**/b-ber-resources/*.js',
    '!**/b-ber-shapes-dublin-core/elements.js',
    '!**/b-ber-shapes-dublin-core/terms.js',
    '!**/b-ber-shapes-dublin-core/index.js',
    '!**/b-ber-shapes-directives/index.js',
    '!**/b-ber-shapes-sequences/index.js',
    '!**/b-ber-shapes-sequences/create-build-sequence.js',
    '!**/b-ber-shapes-sequences/sequences/index.js',
    '!**/b-ber-templates/*.js',
    '!**/b-ber-templates/Ncx/*.js',
    '!**/b-ber-templates/Opf/*.js',
    '!**/b-ber-templates/Ops/*.js',
    '!**/b-ber-templates/Project/*.js',
    '!**/b-ber-templates/Toc/*.js',
    '!**/b-ber-templates/Xhtml/*.js',
    '!**/b-ber-templates/Xml/*.js',
    '!**/b-ber-templates/figures/*.js',
    '!**/jest-transform-upward.js',
    '!**/webpack.config.*.js',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/packages/b-ber-connect/',
    '<rootDir>/coverage/',
    '<rootDir>/demos/',
    '<rootDir>/scripts/',
  ],
  coverageReporters: ['html', 'lcov', 'json'],
  moduleFileExtensions: ['js', 'jsx', 'json'],
  testEnvironment: 'jest-environment-jsdom-global',
  testURL: 'http://localhost/',
}
