version: 2.0

jobs:
  build:
    docker:
      - image: canopycanopycanopy/b-ber:1.0.1
    branches:
      only: main
    working_directory: ~/b-ber
    steps:
      - checkout
      - run: |
          echo $(find . -type f -name package.json -not -path "*/node_modules*" -exec md5sum {} \; | md5sum | cut -d' ' -f1) >> BBER_CACHE_KEY
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "BBER_CACHE_KEY" }}
            - npm-packages-v1-{{ checksum "BBER_CACHE_KEY" }}
      - run: |
          echo NodeJS $(node -v)
          echo npm $(npm -v)

          npm ci --ignore-scripts

          echo Lerna $(./node_modules/.bin/lerna -v)

          # Build readers separately since they're interdependent and require deps installed at package dir for b-ber-reader
          npm run lerna run build -- --scope=@canopycanopycanopy/b-ber-reader-react
          npm run reader:shim
          npm run lerna run build -- --scope="@canopycanopycanopy/{$(ls packages -xm --width=0 | sed 's/ //g' | sed -E 's/b-ber-reader-react,?//')}" --concurrency=2
          npm test -- --maxWorkers=2

          cd ~
          $BBER --version
          $BBER new foo
          cd foo
          $BBER theme list
          $BBER theme set b-ber-theme-serif
          $BBER build reader web
      - save_cache:
          paths:
            - ~/b-ber/node_modules
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "BBER_CACHE_KEY" }}
