/* eslint-disable */

//
// This file is written as-is before the closing `body` elements on the pages
// generated by `bber build --web`.
//

function navigate(dir) {
    var link = document.querySelector('.publication__nav__' + dir + ' a.publication__nav__link');
    if (!link) { return; }

    var href = link.getAttribute('href');
    if (href) {
        window.location.href = href;
    }
}

function navigateNext() {
    navigate('next');
}

function navigatePrev() {
    navigate('prev');
}


function registerNavEvents() {
    // sliding panels
    var tocButton = document.querySelector('.header__item__toggle--toc button');
    var infoButton = document.querySelector('.header__item__toggle--info button');
    var publicationContent = document.querySelector('.publication__contents');

    // slide handlers
    tocButton.addEventListener('click', function() {
        document.body.classList.remove('info--visible');
        document.body.classList.toggle('toc--visible');
    }, false);

    infoButton.addEventListener('click', function() {
        document.body.classList.remove('toc--visible');
        document.body.classList.toggle('info--visible');
    }, false);

    publicationContent.addEventListener('click', function() {
        document.body.classList.remove('toc--visible');
        document.body.classList.remove('info--visible');
        searchInput.classList.remove('publication__search__input--expanded')
    }, false);

    // keyboard navigation
    // TODO: this a good idea? might just end up being annoying for users
    //
    // document.addEventListener('keyup', function(e) {
    //     if (e && e.which) {
    //         if (e.which === 39/* arrow right */) {
    //             navigateNext();
    //         }
    //         if (e.which === 37/* arrow left */) {
    //             navigatePrev();

    //         }
    //     }
    // }, false);
}

window.addEventListener('load', registerNavEvents, false);
