'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _utils = require('@canopycanopycanopy/b-ber-lib/utils');

var epub = {
    portrait: function portrait(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large' + (data.inline ? ' figure__inline figure__inline--portrait ' + data.classes : '') + '"' + (0, _utils.getPagebreakAttribute)(data) + '>\n                <figure id="' + data.id + '">\n                    <div class="figure__items" style="width: 70%; margin: 0 auto;">\n                        ' + (!data.inline ? '<a href="' + data.ref + '.xhtml#ref' + data.id + '">' : '') + '\n                            <img class="portrait" alt="' + data.alt + '" src="../images/' + data.source + '" style="width: 100%; max-width: 100%; height: auto;"/>\n                        ' + (!data.inline ? '</a>' : '') + '\n                        <div class="figcaption" style="width: 100%; max-width: 100%; height: auto;">\n                            <p class="small">' + data.caption + '</p>\n                        </div>\n                    </div>\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },
    landscape: function landscape(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large' + (data.inline ? ' figure__inline figure__inline--landscape ' + data.classes : '') + '"' + (0, _utils.getPagebreakAttribute)(data) + '>\n                <figure id="' + data.id + '">\n                    <div class="figure__items">\n                        ' + (!data.inline ? '<a href="' + data.ref + '.xhtml#ref' + data.id + '">' : '') + '\n                            <img class="landscape" alt="' + data.alt + '" src="../images/' + data.source + '" style="max-width: 100%;"/>\n                        ' + (!data.inline ? '</a>' : '') + '\n                        <div class="figcaption" style="max-width: 100%;">\n                            <p class="small">' + data.caption + '</p>\n                        </div>\n                    </div>\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },

    'portrait-high': function portraitHigh(data) {
        // eslint-disable-line func-names
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large' + (data.inline ? ' figure__inline figure__inline--portrait-high ' + data.classes : '') + '"' + (0, _utils.getPagebreakAttribute)(data) + '>\n                <figure id="' + data.id + '">\n                    <div class="figure__items" style="width: 60%; margin: 0 auto;">\n                        ' + (!data.inline ? '<a href="' + data.ref + '.xhtml#ref' + data.id + '">' : '') + '\n                            <img class="portrait-long" alt="' + data.alt + '" src="../images/' + data.source + '" style="width: 100%; max-width: 100%; height: auto;"/>\n                        ' + (!data.inline ? '</a>' : '') + '\n                        <div class="figcaption" style="width: 100%; max-width: 100%; height: auto;">\n                            <p class="small">' + data.caption + '</p>\n                        </div>\n                    </div>\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },
    square: function square(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large' + (data.inline ? ' figure__inline figure__inline--square ' + data.classes : '') + '"' + (0, _utils.getPagebreakAttribute)(data) + '>\n                <figure id="' + data.id + '">\n                    <div class="figure__items" style="width: 85%; margin: 0 auto;">\n                        ' + (!data.inline ? '<a href="' + data.ref + '.xhtml#ref' + data.id + '">' : '') + '\n                            <img class="square" alt="' + data.alt + '" src="../images/' + data.source + '" style="width: 100%; max-width: 100%; height: auto;"/>\n                        ' + (!data.inline ? '</a>' : '') + '\n                        <div class="figcaption" style="width: 100%; max-width: 100%; height: auto;">\n                            <p class="small">' + data.caption + '</p>\n                        </div>\n                    </div>\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },
    audio: function audio(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large">\n                <figure id="' + data.id + '">\n\n                    <div class="figure__items">\n\n                        <div class="audio">\n                            <audio ' + data.attrString + '>\n                                ' + data.sourceElements + '\n                                <div class="media__fallback__' + data.mediaType + ' media__fallback--image figure__small--landscape figure__small">\n                                    <figure>\n                                        <img src="' + data.poster + '" alt="Media fallback image"/>\n                                    </figure>\n                                </div>\n                                <p class="media__fallback__' + data.mediaType + ' media__fallback--text">Your device does not support the HTML5 ' + data.mediaType + ' API.</p>\n                            </audio>\n                        </div>\n\n                        <div class="figcaption" style="max-width: 100%;">\n                            <p class="small">\n                                ' + (data.caption ? data.caption + '<br/>' : '') + '\n                                <a href="' + data.ref + '.xhtml#ref' + data.id + '">Return</a>\n                            </p>\n                        </div>\n\n                    </div>\n\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },
    video: function video(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large">\n                <figure id="' + data.id + '">\n\n                    <div class="figure__items">\n\n                        <div class="video">\n                            <video ' + data.attrString + '>\n                                ' + data.sourceElements + '\n                                <div class="media__fallback__' + data.mediaType + ' media__fallback--image figure__small--landscape figure__small">\n                                    <figure>\n                                        <img src="' + data.poster + '" alt="Media fallback image"/>\n                                    </figure>\n                                </div>\n                                <p class="media__fallback__' + data.mediaType + ' media__fallback--text">Your device does not support the HTML5 ' + data.mediaType + ' API.</p>\n                            </video>\n                        </div>\n\n                        <div class="figcaption" style="max-width: 100%;">\n                            <p class="small">\n                                ' + (data.caption ? data.caption + '<br/>' : '') + '\n                                <a href="' + data.ref + '.xhtml#ref' + data.id + '">Return</a>\n                            </p>\n                        </div>\n\n                    </div>\n\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    },
    iframe: function iframe(data) {
        return (!data.inline ? '<section epub:type="loi" title="Figures" class="chapter figures">' : '') + '\n            <div class="figure__large">\n                <figure id="' + data.id + '">\n                    <div class="figure__items">\n                        <div class="iframe">\n                            <iframe src="' + (0, _utils.encodeQueryString)(data.source) + '" />\n                        </div>\n\n                        <div class="figcaption" style="max-width: 100%;">\n                            <p class="small">\n                                ' + (data.caption ? data.caption + '<br/>' : '') + '\n                                <a href="' + data.ref + '.xhtml#ref' + data.id + '">Return</a>\n                            </p>\n                        </div>\n                    </div>\n                </figure>\n            </div>\n        ' + (!data.inline ? '</section>' : '');
    }
}; /* eslint-disable max-len */

exports.default = epub;