version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    target_branch: 'main'
    allowed_updates:
      - match:
          update_type: 'security'
    default_reviewers:
      - 'msimmer'
    default_labels:
      - 'security'
